<?php

function items_faceted_views_pre_render(&$view) {
  if ($view->name == 'items_faceted' && $view->current_display == 'page_1') {
    preg_match("/(.*) \\| AITopics/", page_title_page_get_title(), $matches);
    if(count($matches) > 1) {
        $view->build_info['title'] = $matches[1];
    }
  }
}

function items_faceted_page_title_pattern_alter(&$pattern, &$types) {
    if(arg(0) == "items" && !array_key_exists('f', $_GET)) { 
        $pattern = "Items | AITopics";
    }
}

